### ISSUE TITLE
[CHORE] Sort Link cards

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#393] opened 2023-04-05 17:26 UTC
### What would you like to share or ask?

Currently, the link cards are showing in the order as they are added, it would be better if we can sort them in Alphabetical order

### Additional information

![image](https://user-images.githubusercontent.com/78981177/230157404-98950d5b-9001-4fa7-bdf5-a49cd4e32574.png)

**Comment by OscarFMdev** [comment] 2023-04-05 22:35
## Hello, @rupali-codes 
I hope you're doing well, I have already sent a PR for this issue, this is the first time I contribute to an Open Source project, I think I had to ask for this PR first, but the issue is fixed in #394. 
### Thank you for your patience and for letting me contribute!

**Closed** 2023-04-06 06:19 UTC
Labels: enhancement, good first issue, frontend, up for grabs, chore
