### ISSUE TITLE
[Feature] <Maintainer section on website>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#500] opened 2023-05-01 19:37 UTC
### Description

It would be helpful to have a section labeled "Maintainers" with a little paragraph about them. In doing so, maintainers can use it as a tangible reference for job applications that request samples or something to refer to in job interviews(see screenshot for reference).  

### Screenshots

![example # 1](https://user-images.githubusercontent.com/105683440/235517303-9339d1c8-2ac8-417c-adf3-0f071a8cf8bf.png)
![example 2](https://user-images.githubusercontent.com/105683440/235517330-795c2bac-6a09-4804-851b-1bf1bf3673c0.png)

**Comment by rupali-codes** [comment] 2023-05-02 12:10
@CBID2 We are designing the landing as shared in discord, i guess its better if we add this in landing page right?

**Comment by Divyansh-0** [comment] 2023-05-02 12:36
Can i design this section ??

**Comment by CBID2** [comment] 2023-05-02 13:08
> @CBID2 We are designing the landing as shared in discord, i guess its better if we add this in landing page right?

Yes.

**Comment by ujjawaltyagii** [comment] 2023-05-02 23:16
> ### Description
> It would be helpful to have a section labeled "Maintainers" with a little paragraph about them. In doing so, maintainers can use it as a tangible reference for job applications that request samples or something to refer to in job interviews(see screenshot for reference).
> 
> ### Screenshots
> ![example # 1](https://user-images.githubusercontent.com/105683440/235517303-9339d1c8-2ac8-417c-adf3-0f071a8cf8bf.png) ![example 2](https://user-images.githubusercontent.com/105683440/235517330-795c2bac-6a09-4804-851b-1bf1bf3673c0.png)
> 
> ### Additional Information
> _No response_

@CBID2 that's a fantastic idea !

**Comment by ujjawaltyagii** [comment] 2023-05-02 23:17
@CBID2 that's a fantastic idea !

**Comment by CBID2** [comment] 2023-05-03 00:18
> Can i design this section ??
> 
> 

Sure @Divyansh-0! 😁

**Comment by Divyansh-0** [comment] 2023-05-03 10:22
> > Can i design this section ??
> 
> Sure @Divyansh-0! 😁

So should i go on and add it to existing webpage because i dont know how the landing page is being designed

**Comment by rupali-codes** [comment] 2023-05-03 16:30
> > > Can i design this section ??
> > 
> > 
> > Sure @Divyansh-0! 😁
> 
> So should i go on and add it to existing webpage because i dont know how the landing page is being designed

Are you talking about design or implementation as well?

**Comment by Divyansh-0** [comment] 2023-05-05 05:11
@rupali-codes I can design it separately if you want but in implementation where should i place it??

**Comment by rupali-codes** [comment] 2023-05-05 17:29
> @rupali-codes I can design it separately if you want but in implementation where should i place it??

You can create a sperate page

**Comment by Divyansh-0** [comment] 2023-05-07 09:41
> > @rupali-codes I can design it separately if you want but in implementation where should i place it??
> 
> You can create a sperate page named about us then we'll also put some more information about the site as well,

Okk i will update once i finish it

**Comment by rupali-codes** [comment] 2023-05-14 05:07
Hey @Divyansh-0, are you still working on it? Any updates?

**Comment by Divyansh-0** [comment] 2023-05-14 06:53
> Hey @Divyansh-0, are you still working on it? Any updates?

Yeah i was working on it but I have exams now🥲

**Comment by rupali-codes** [comment] 2023-05-14 10:49
> > Hey @Divyansh-0, are you still working on it? Any updates?
> 
> Yeah i was working on it but I have exams now🥲

Ohh, it's fine and Good luck for your exams ☺️☺️

**Comment by Noothan-am** [comment] 2023-05-20 13:03
hey @rupali-codes is this issue still open?

**Comment by CBID2** [comment] 2023-05-20 15:05
> hey @rupali-codes is this issue still open?

Yes it is! :) Do you want to work on it?

**Comment by Noothan-am** [comment] 2023-05-20 16:13
yes can i start working on it ?

**Comment by CBID2** [comment] 2023-05-20 17:45
> yes, please assign it to me

Done @Noothan-am

**Comment by rupali-codes** [comment] 2023-05-20 18:09
> yes, please assign it to me

Are you a GSSoC contributor?

**Comment by Noothan-am** [comment] 2023-05-20 18:10
yes

**Comment by rupali-codes** [comment] 2023-05-20 18:40
> yes

Cool, please work on one issue at a time :)

**Comment by Noothan-am** [comment] 2023-05-21 13:38
hey, can you provide steps to reproduce this issue?

**Comment by CBID2** [comment] 2023-05-21 16:00
> hey @CBID2, is maintainers page to be created from scratch on LinksHub website...? 

Check out [this comment](https://github.com/rupali-codes/LinksHub/issues/500#issuecomment-1536565758)for ideas.

**Comment by CBID2** [comment] 2023-05-24 04:10
Hey @Noothan-am. Any updates?

**Comment by Phyozawhein** [comment] 2023-05-24 04:13
Hi, I'd like to help. Are we still working on the design or implementing it ?

**Comment by CBID2** [comment] 2023-05-24 04:17
> Hi, I'd like to help. Are we still working on the design or implementing it ?

Check out this [comment](https://github.com/rupali-codes/LinksHub/issues/500#issuecomment-1536565758) for context @Phyozawhein. Also, for protocol reasons, I have to ask if you are in GSSOC this year?

**Comment by Phyozawhein** [comment] 2023-05-24 04:18
> > Hi, I'd like to help. Are we still working on the design or implementing it ?
> 
> Check out this [comment](https://github.com/rupali-codes/LinksHub/issues/500#issuecomment-1536565758) for context @Phyozawhein. Also, for protocol reasons, I have to ask if you are in GSSOC this year?

Yes I am in GSSOC.

**Comment by Noothan-am** [comment] 2023-05-24 05:10
hey 

> Hey @Noothan-am. Any updates? @Phyozawhein wants to work on this issue.

Hey @CBID2, I am working on this, but I just wanted to clarify if the "About Us" page needs to be integrated into the home page only, right?

on this page..?
![image](https://github.com/rupali-codes/LinksHub/assets/100135382/0ac124cd-8f13-4109-a95e-bcbd2fd2ff62)

**Comment by CBID2** [comment] 2023-05-24 05:12
> hey 
> 
> 
> 
> > Hey @Noothan-am. Any updates? @Phyozawhein wants to work on this issue.
> 
> 
> 
> Hey @CBID2, I am working on this, but I just wanted to clarify if the "About Us" page needs to be integrated into the home page only, right?
> 
> 
> 
> on this page..?
> 
> ![image](https://github.com/rupali-codes/LinksHub/assets/100135382/0ac124cd-8f13-4109-a95e-bcbd2fd2ff62)
> 
> 

Definitely @Noothan-am ! :)

**Comment by Noothan-am** [comment] 2023-05-24 06:26
> > hey
> > > Hey @Noothan-am. Any updates? @Phyozawhein wants to work on this issue.
> > 
> > 
> > Hey @CBID2, I am working on this, but I just wanted to clarify if the "About Us" page needs to be integrated into the home page only, right?
> > on this page..?
> > ![image](https://user-images.githubusercontent.com/100135382/240492920-0ac124cd-8f13-4109-a95e-bcbd2fd2ff62.png)
> 
> @Noothan-am, since it needs to be on a separate page, I guess having a drop-down menu-like feature would suffice

drop-down menu should be beside those github, twitter links..?

**Comment by rupali-codes** [comment] 2023-05-24 14:59
@Noothan-am I guess we can integrate this in landing page itself

**Comment by Noothan-am** [comment] 2023-05-24 17:05
@rupali-codes , here...?

![image](https://github.com/rupali-codes/LinksHub/assets/100135382/81d9bb21-5b9a-4d55-b41a-207e06fdd391)

**Comment by CBID2** [comment] 2023-05-24 17:44
> @rupali-codes , here...?
> 
> ![image](https://user-images.githubusercontent.com/100135382/240686797-81d9bb21-5b9a-4d55-b41a-207e06fdd391.png)

Yeah @Noothan-am, I can picture it right before the Frontend tab

**Comment by Noothan-am** [comment] 2023-05-24 18:01
> Yeah @Noothan-am, I can picture the About Us right before the Frontend tab. I'm thinking that within the About Us section, there can be an "Our Origin Story" tab, "Meet the Maintainers" tab, "Our Contributors", and "Contact Us" tab. Something like this: <img alt="About Us section example" width="1255" src="https://user-images.githubusercontent.com/105683440/240699148-ce7256f8-09ba-4ee9-b426-92e7d2d5816d.png">

Got it. so in these pages dummy data to be added or you will provide what contents to add? like maintainers paragraph, images

**Comment by CBID2** [comment] 2023-05-25 00:48
> > Yeah @Noothan-am, I can picture the About Us right before the Frontend tab. I'm thinking that within the About Us section, there can be an "Our Origin Story" tab, "Meet the Maintainers" tab, "Our Contributors", and "Contact Us" tab. Something like this: <img alt="About Us section example" width="1255" src="https://user-images.githubusercontent.com/105683440/240699148-ce7256f8-09ba-4ee9-b426-92e7d2d5816d.png">
> 
> Got it. so in these pages dummy data to be added or you will provide what contents to add? like maintainers paragraph, images

Good question @Noothan-am! :) @rupali-codes, would you work with me on writing our bios for the Maintainers section?

**Comment by Noothan-am** [comment] 2023-05-26 06:59
hey @CBID2, let me know when you finish bios content. so that i can proceed further

**Comment by CBID2** [comment] 2023-05-26 12:27
> hey @CBID2, let me know when you finish bios content. so that i can proceed further 

I sure will @Noothan-a.

**Comment by CBID2** [comment] 2023-05-26 23:25
> > hey @CBID2, let me know when you finish bios content. so that i can proceed further 
> 
> I sure will @Noothan-a. 

Hey @Noothan-am! 😊 Here's a [link to my bio](https://docs.google.com/document/d/12DoudyVeTOlq2zaf9Gz2wKyf3FFwKMFcqoBpl60_QyE/edit)

**Comment by Noothan-am** [comment] 2023-05-27 05:26
> > > hey @CBID2, let me know when you finish bios content. so that i can proceed further
> > 
> > 
> > I sure will @Noothan-a.
> 
> Hey @Noothan-am! 😊 Here's a [link to my bio](https://docs.google.com/document/d/12DoudyVeTOlq2zaf9Gz2wKyf3FFwKMFcqoBpl60_QyE/edit)

hey @CBID2, only yours to be added? and UI for this page should be as mentioned in issue here👉[https://github.com/rupali-codes/LinksHub/issues/500#issue-1691258901] or my wish.??

**Comment by CBID2** [comment] 2023-05-27 05:27
> > > > hey @CBID2, let me know when you finish bios content. so that i can proceed further
> 
> > > 
> 
> > > 
> 
> > > I sure will @Noothan-a.
> 
> > 
> 
> > Hey @Noothan-am! 😊 Here's a [link to my bio](https://docs.google.com/document/d/12DoudyVeTOlq2zaf9Gz2wKyf3FFwKMFcqoBpl60_QyE/edit)
> 
> 
> 
> hey @CBID2, only yours to be added? and UI for this page should be as mentioned in issue here👉[https://github.com/rupali-codes/LinksHub/issues/500#issue-1691258901] or my wish.??

We got to add @rupali-codes’ bio too @Noothan-am.

**Comment by rupali-codes** [comment] 2023-05-27 14:15
@Noothan-am & @CBID2 this should be done along with [landing page issue](https://vercel.com/docs/concepts/deployments/git/vercel-for-github)

**Comment by Anmol-Baranwal** [comment] 2023-06-25 20:17
@rupali-codes 
Can I help with this? I have already created a contributors page and I am willing to create something different for maintainers.

> I will work, if the person assigned is willing for the same.

**Comment by Noothan-am** [comment] 2023-06-26 17:32
hey @Anmol-Baranwal, I am still working on this. I have to integrate the landing page to main website.

**Comment by Anmol-Baranwal** [comment] 2023-06-26 17:38
> hey @Anmol-Baranwal, I am still working on this. I have to integrate the landing page to main website.

So, is the page created? No worries, contribute it. Feel free to ask me, if you need any assistance.

**Comment by k-deepak04** [comment] 2023-06-30 09:06
@Noothan-am any updates bro? 
please try to complete this as soon as possible

**Comment by k-deepak04** [comment] 2023-07-08 19:09
closing this due to no updates after a long time.

**Comment by Anmol-Baranwal** [comment] 2023-07-08 19:26
> closing this due to no updates after a long time.

Assign me, I will complete this.

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/ad9c4eb6-4a16-410c-9750-27ef3d3f4da5)

**Comment by CBID2** [comment] 2023-07-08 19:27
You're assigned @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment] 2023-07-09 12:06
@CBID2 @rupali-codes 
I would need following information.

- Where should I link this page to? On the landing page.

- Will there be any difference between the design for the owner (`rupali`) and the maintainers, or should it be the same for all?

- Apart from the GitHub Profile and LinkedIn Profile, what other information do I need to display for each maintainer?

- Do you have some explicit designs you want me to implement? 

It may take some time, as I will try to implement a new and innovative design. However, please let me know if you have a specific design.

**Comment by rupali-codes** [comment] 2023-07-14 08:43
@Anmol-Baranwal can we do one thing, in the contributors page, can we add something like a tag for maintainers? 

for maintainers it could be, **maintainer** and for contributors it could be **contributor**

@CBID2 @k-deepak04 what do you think?

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/99496aab-dcab-468d-a85e-742e33b17807)

**Comment by Anmol-Baranwal** [comment] 2023-07-14 09:24
@rupali-codes 
Let me know what you prefer. (You can reply there as well)
https://jam.dev/c/5364ee67-522d-4745-9972-eeb02721309f

**Comment by k-deepak04** [comment] 2023-07-14 19:02
> @Anmol-Baranwal can we do one thing, in the contributors page, can we add something like a tag for maintainers?
> 
> for maintainers it could be, **maintainer** and for contributors it could be **contributor**
> 
> @CBID2 @k-deepak04 what do you think?
> 
> ![image](https://user-images.githubusercontent.com/78981177/253521180-99496aab-dcab-468d-a85e-742e33b17807.png)

i guess this would be good as maintainers are also contributors, in the same section we can showcase our contributions and also people can know this is mentor and this is project admin, while seeing the contributor section.

**Comment by CBID2** [comment] 2023-07-14 19:05
> > @Anmol-Baranwal can we do one thing, in the contributors page, can we add something like a tag for maintainers?
> 
> > 
> 
> > for maintainers it could be, **maintainer** and for contributors it could be **contributor**
> 
> > 
> 
> > @CBID2 @k-deepak04 what do you think?
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/78981177/253521180-99496aab-dcab-468d-a85e-742e33b17807.png)
> 
> 
> 
> i guess this would be good as maintainers are also contributors, in the same section we can showcase our contributions and also people can know this is mentor and this is project admin, while seeing the contributor section.

I second this @Anmol-Baranwal and @k-deepak04. Adding a symbol would make the roles more distinctive.

**Closed** 2023-07-23 06:00 UTC
Labels: goal: new-feature, frontend, design, chore, gssoc23, level2
