### ISSUE TITLE
[BUG] < Error GitHub Action for Close Old PRs>

### ISSUE THREAD

**Issue by CBID2** [rupali-codes/LinksHub#722] opened 2023-05-25 06:22 UTC
### Description

I found this [error](https://github.com/rupali-codes/LinksHub/actions/runs/5074710626) while scrolling through some pull requests. I think this is why the auto-merge option has stopped working.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Isha988** [comment] 2023-05-26 07:52
@CBID2 I want to work on this issue, it may take a little more time to complete as I have never worked on GitHub actions but want to learn more about it.

**Comment by CBID2** [comment] 2023-05-26 12:40
> @CBID2 I want to work on this issue, it may take a little more time to complete as I have never worked on GitHub actions but want to learn more about it.

I just assigned you another issue. Finish that one before we continue the conversation about this issue.

**Comment by Isha988** [comment] 2023-05-26 12:42
> > @CBID2 I want to work on this issue, it may take a little more time to complete as I have never worked on GitHub actions but want to learn more about it.
> 
> I just assigned you another issue. Finish that one before we continue the conversation about this issue.

Ya sure no problem.

**Comment by ujjawaltyagii** [comment] 2023-05-26 15:01
@CBID2 I have an idea - <br>
generally working with github actions :
- We create a GHA workflow with that would run once per day (or manually using [on.workflow_dispatch]
<b>
- The error you're encountering is due to the missing module '@octokit/rest'. It seems that the version of the 'actions/github-script' action you're using is incompatible with the code that relies on the '@octokit/rest' module.  </b>

<br>
<br>
- You can assign this issue to me I can fix this.  <br> <br>
- Now you might think that I am already assigned with a issue but I think this is a important `Github workflow Action` as now due to GSSoC we are getting a lot of PRs so we should give it priory to make PRs manageable.
<br>
<br>
I will wrap up this issue quickly and will resume to my other assigned issue right now.
<br>
- I am a GSSoC contributor so you can keep the label as it is !

**Comment by CBID2** [comment] 2023-05-26 15:09
Go for it @ujjawaltyagii! By the way, are you a maintainer for LinksHub?

**Comment by ujjawaltyagii** [comment] 2023-05-26 15:19
@CBID2 Been contributing actively to the LinksHub from last 3 months still haven't got that privilege yet 😅

**Comment by CBID2** [comment] 2023-05-26 15:21
> @CBID2 Been contributing actively to the LinksHub from last 3 months still haven't got that privilege yet 😅

@rupali-codes, I think we should granted @ujjawaltyagii the role of maintainer. They've been making pretty effective contributions to this project, and we could use more help lol 😂

**Comment by rupali-codes** [comment] 2023-05-27 14:05
@CBID2 I have been noticing :), also, should we turn LinksHub into github org?

**Comment by rupali-codes** [comment] 2023-05-27 14:10
@CBID2 This issue is duplicate of #715 👀

**Comment by CBID2** [comment] 2023-05-27 14:54
> @CBID2 This issue is duplicate of #715 👀
Hey @rupali-codes. They are different. @ujjawaltyagii just managed to find a way to address both

**Comment by rupali-codes** [comment] 2023-05-28 06:02
> > @CBID2 This issue is duplicate of #715 👀
> > Hey @rupali-codes. They are different. @ujjawaltyagii just managed to find a way to address both with one solution

ok

**Closed** 2023-05-28 07:13 UTC
Labels: bug, up for grabs, gssoc23, level3
