### ISSUE TITLE
[BUG] Highlight the selected category

### ISSUE THREAD

**Issue by Olaleye-Blessing** [rupali-codes/LinksHub#1747] opened 2023-10-02 08:26 UTC
### Description

It's hard to know which link is selected from the navbar because the selected category is not been highlighted. 

### Screenshots

<img width="1465" alt="Screenshot 2023-10-02 at 09 20 54" src="https://github.com/rupali-codes/LinksHub/assets/70102539/afb7e364-5db3-4571-862a-528937563dc2">

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment] 2023-10-02 10:57
@Olaleye-Blessing 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

Good luck. We are here to help you at every step, even with the code. Feel free to ask.

**Comment by Anmol-Baranwal** [comment] 2023-10-02 10:59
@Olaleye-Blessing 
Please don't create new issues unless you have completed working on the existing ones.

**Comment by Anmol-Baranwal** [comment] 2023-10-02 11:24
@Olaleye-Blessing 
#1687 is similar to this. I just noticed.

Did you check the existing issues?
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/03b6b4bf-cb87-4b6e-ae4f-344575e616f4)

Don't worry, we will keep the PR open for now. If that issue is closed, then we will move forward with your PR.

**Comment by Olaleye-Blessing** [comment] 2023-10-02 11:28
> @Olaleye-Blessing #1687 is similar to this. I just noticed.
> 
> Did you check the existing issues? ![image](https://user-images.githubusercontent.com/74038190/271956951-03b6b4bf-cb87-4b6e-ae4f-344575e616f4.png)
> 
> Don't worry, we will keep the PR open for now. If that issue is closed, then we will move forward with your PR.

Yes, I checked. My mind must have skipped it.

**Comment by Olaleye-Blessing** [comment] 2023-10-02 11:33
> > Yes, I checked. My mind must have skipped it.
> 
> No worries.

I've linked the 2 issues to my PR.

**Comment by Anmol-Baranwal** [comment] 2023-10-02 11:39
> > > Yes, I checked. My mind must have skipped it.
> > 
> > 
> > No worries.
> 
> I've linked the 2 issues to my PR.

Yeah, I saw. Let us wait to see if the author of that issue would contribute or not.

**Comment by Anmol-Baranwal** [comment] 2023-10-03 06:30
duplicate of #1687 

Closing this!

**Closed by Anmol-Baranwal** 2023-10-03 06:30 UTC
Labels: goal: new-feature, 🚀 ready, priority: medium, hacktoberfest
