### ISSUE TITLE
[BUG] Main Accordion is Not working 

### ISSUE THREAD

**Issue by arslan-ahm** [rupali-codes/LinksHub#2567] opened 2024-11-20 14:11 UTC
### Description

Whenever we open accordion it never closes. No matter How much try to close it, It remains open.

### Screenshots

![image](https://github.com/user-attachments/assets/47e1b624-2700-4df5-9903-546e6be33479)
![image](https://github.com/user-attachments/assets/3fc3d805-8985-4e19-b459-8f0d43190700)

### Any additional information?

https://github.com/user-attachments/assets/7d3334fb-0b71-474d-af9e-739a8ff54928

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Lucifer4255** [comment] 2024-11-21 08:26
can i work in this issue?

**Comment by NayanUnni95** [comment] 2024-11-21 12:19
I would like to work on this.

**Comment by rupali-codes** [comment] 2024-12-02 13:46
Hey @arslan-ahm. Sorry for the delay, are you still interested in working on this issue?

**Comment by SanjitSG** [comment] 2024-12-04 18:17
Hey @rupali-codes, Can i work on this issue?

**Comment by SanjitSG** [comment] 2024-12-04 19:49
**Problem**: Categories were not closing as expected when toggled. After investigating, I identified that the problem was due to unnecessary re-renders caused by the `categoryData` prop being passed into `useEffect`.

**Fix**: I removed categoryData from the useEffect dependency array and memoized the sortedSubcategoryList to optimize performance. This ensures that the component no longer resets its state unnecessarily and the accordion behaves as expected.

I’ve already implemented and tested the solution locally, and everything seems to be working as expected.

Would you mind assigning the issue to me so I can open a PR with this fix? Let me know if you have any questions or need further clarification.

Thanks!

https://github.com/user-attachments/assets/8bb54792-dae1-40b0-b339-b33b8fc5a49b

**Comment by SanjitSG** [comment] 2024-12-04 20:25
Hi, I’ve noticed the problem with the accordion behavior in the sidebar, where the categories don’t close as expected. I believe this is due to unnecessary re-renders triggered by the `categoryData` prop being passed into `useEffect`.

I’ve already identified the fix, which involves removing categoryData from the useEffect dependency array and memoizing the sortedSubcategoryList. This should optimize the performance and fix the behavior.

I would like to work on this issue.

take

https://github.com/user-attachments/assets/700ef95d-4f2e-424a-ab79-290ff9aa858f

**Comment by rupali-codes** [comment] 2024-12-09 18:17
Hey @SanjitSG thanks, we appreciate your time. Feel free to raise a PR whenever you get time.

**Closed** 2024-12-11 11:36 UTC
Labels: bug, priority: medium
