### ISSUE TITLE
[BUG] searchbar query persist even after clearing the searchbar

### ISSUE THREAD

**Issue by k-deepak04** [rupali-codes/LinksHub#1518] opened 2023-08-08 09:10 UTC
### Description

after writien anything the searchbar query still persist there in the url

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/96341431/2653b0f1-2450-4634-9b13-2fc5983511b3

### Any additional information?

there is one more issue that all dropdown open up after clearing the searched word.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by k-deepak04** [comment] 2023-08-08 09:10
@CBID2 @rupali-codes please check this, it's very imp issue i guess.

**Comment by k-deepak04** [comment] 2023-08-08 09:11
please assign that i can quickly start working on this

**Comment by rupali-codes** [comment] 2023-08-24 17:24
@k-deepak04 are you willing to raise a sperate PR or shall we open this issue for others?

**Comment by k-deepak04** [comment] 2023-08-25 02:36
@rupali-codes please assign it to other, I'll be reviewing the code and be active but not that much as many things are going at my side, but as I get time I'll also contribute definitely.

**Comment by shreedhar37** [comment] 2023-09-02 14:32
https://github.com/rupali-codes/LinksHub/assets/55444468/efdcfbd6-fbb2-470b-9680-0e2b3d25c528

@rupali-codes  @k-deepak04 let me know what do you think about this solution

**Comment by k-deepak04** [comment] 2023-09-02 14:59
@shreedhar37 seems perfect to me :)

**Comment by CBID2** [comment] 2023-09-02 18:19
> 
> 
> https://github.com/rupali-codes/LinksHub/assets/55444468/efdcfbd6-fbb2-470b-9680-0e2b3d25c528
> 
> 
> 
> @rupali-codes  @k-deepak04 let me know what do you think about this solution
> 
> 
Same here.

**Comment by CBID2** [comment] 2023-09-02 18:19
@shreedhar37, do you want to be assigned to this issue?

**Comment by shreedhar37** [comment] 2023-09-02 18:21
Yes @CBID2  I can solve this. Please assign me this issue.

**Comment by CBID2** [comment] 2023-09-02 18:22
You're assigned @shreedhar37

**Comment by shreedhar37** [comment] 2023-09-03 13:18
> You're assigned @shreedhar37 

Please assign this issue to someone else. I am not available to solve this issue.

**Comment by Ameya02** [comment] 2023-09-23 18:31
I would like to assign to this issue

**Comment by rupali-codes** [comment] 2023-09-24 15:03
> I would like to assign to this issue

Sure, thanks. Assigning to you!

**Comment by CBID2** [comment] 2023-09-30 01:36
Any updates on this @Ameya02?

**Comment by Ameya02** [comment] 2023-09-30 06:58
[github-linkshub.webm](https://github.com/rupali-codes/LinksHub/assets/65841021/3f73cdab-07fc-4e48-8c41-04a57b95b883)
Here is my solution

**Comment by Ameya02** [comment] 2023-09-30 07:21
https://github.com/rupali-codes/LinksHub/assets/65841021/13e493dc-7090-41e4-bad9-89bd3e53beda

Here is my solution

**Comment by CBID2** [comment] 2023-09-30 08:35
> 
> 
> https://github.com/rupali-codes/LinksHub/assets/65841021/13e493dc-7090-41e4-bad9-89bd3e53beda
> 
> 
> 
> Here is my solution

Looks great @Ameya02.

**Comment by Ameya02** [comment] 2023-10-01 05:23
Will this will be counted for hackoctoberfest?

**Comment by CBID2** [comment] 2023-10-01 12:30
> Will this will be counted for hacktoberfest?

It can be @Ameya02 if you do the PR during this month.

**Comment by Ameya02** [comment] 2023-10-01 14:11
Yes I will do today it

**Comment by rupali-codes** [comment] 2023-10-01 16:16
> Yes I will do today it

alright, thanks

**Comment by Anmol-Baranwal** [comment] 2023-10-02 11:53
We need to add hacktoberfest-accepted on the PR only if the repo doesn't contains the hacktoberfest topics, and only on PRs not issues.

In this case, there are hacktoberfest topics in the repo.

**Comment by Anmol-Baranwal** [comment] 2023-10-02 11:54
I've confirmed it in the official discord channel.

**Comment by CBID2** [comment] 2023-10-02 13:48
Ooh sorry @k-deepak04. It's been a while since you responded about this issue, so I assigned it to @Ameya02. Sadly, I'm going to have to close your PR.

**Comment by Anmol-Baranwal** [comment] 2023-10-03 05:19
The PR is merged, this issue was not linked.

Closing this!

**Closed by Anmol-Baranwal** 2023-10-03 05:19 UTC
Labels: bug, chore, 🚀 ready, hacktoberfest
