### ISSUE TITLE
[Feature]: Horizontal Pagination Overlaps Content - Suggest Vertical Placement

### ISSUE THREAD

**Issue by harmeetsingh11** [rupali-codes/LinksHub#1908] opened 2023-10-08 16:05 UTC
### Description

**Current Behavior:**
The pagination on the page is currently displayed horizontally in the middle of the content, which results in it covering some of the content. This layout is not aesthetically pleasing and may interfere with the user experience.

**Suggested Improvement:**
We propose changing the pagination layout to be displayed vertically to the right of the page content. This will not only improve the visual appeal but also prevent content from being covered or obscured by the pagination controls.

### Steps to Reproduce

1. Visit the page with pagination.
2. Observe how the pagination is currently displayed horizontally in the middle of the content.

### Expected Behavior

The pagination should be displayed vertically to the right of the page content, ensuring that it does not cover or obscure any content.

### Screenshots

![LinksHub-Frontend-colors](https://github.com/rupali-codes/LinksHub/assets/130365071/167d8ff8-3637-4c0d-87b9-d74a09ae3eb0)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment] 2023-10-09 07:02
@harmeetsingh11 
Thanks for the suggestion, it is already under process.

Duplicate of https://github.com/rupali-codes/LinksHub/issues/1833#issuecomment-1750310914

Closing this!

**Closed by Anmol-Baranwal** 2023-10-09 07:02 UTC
Labels: 🔒 locked, priority: high
