### ISSUE TITLE
[Add] Boxicons

### ISSUE THREAD

**Issue by Oyebolade** [rupali-codes/LinksHub#539] opened 2023-05-12 16:43 UTC
### Site URL

https://boxicons.com/

### Description of the above provided site

Boxicons is a versatile collection of over 2,000 elegant vector icons, enhancing websites, apps, and digital projects. With clean lines and sharp edges, these icons seamlessly integrate with diverse design styles. Customize and bring your creative vision to life with Boxicons.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by rupali-codes** [comment] 2023-05-13 18:09
Hey @parma1111, i'm really glad to see your love for LinksHub, appreciate your contributions. But i have some suggestions for you. please check if the Owner of the issue is willing the to work on the issue or not, if not then you can either ask for you to assign the issue or can directly make the PR. But in case owner of the issue is willing to work on that, it would be assigned to them. Though you have created PR for this issue, but please keep this in mind. Thanks ☺️

**Comment by parma1111** [comment] 2023-05-14 05:20
> Hey @parma1111, i'm really glad to see your love for LinksHub, appreciate your contributions. But i have some suggestions for you. please check if the Owner of the issue is willing the to work on the issue or not, if not then you can either ask for you to assign the issue or can directly make the PR. But in case owner of the issue is willing to work on that, it would be assigned to them. Though you have created PR for this issue, but please keep this in mind. Thanks ☺️

sure

**Closed** 2023-05-14 16:17 UTC
Labels: add link, chore
