### ISSUE TITLE
[Add] PlanetScale Database in Database

### ISSUE THREAD

**Issue by Hrithik0112** [rupali-codes/LinksHub#2014] opened 2023-10-17 10:30 UTC
### Site URL

https://planetscale.com/

### Description of the above provided site

PlanetScale is a MySQL-compatible serverless database that brings you scale, performance, and reliability — without sacrificing developer experience.
With PlanetScale, you get the power of horizontal sharding, non-blocking schema changes, and many more powerful database features without the pain of implementing them.

### Category

Backend

### Sub Category

"Database"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by Anmol-Baranwal** [comment] 2023-10-17 15:05
duplicate of #1995 

Closing this!

**Closed by Anmol-Baranwal** 2023-10-17 15:05 UTC
Labels: goal: new-link, 🔒 locked, priority: low, chore
