### ISSUE TITLE
[Feature] Dockerize linksHub

### ISSUE THREAD

**Issue by shraddha761** [rupali-codes/LinksHub#1187] opened 2023-06-28 10:40 UTC
### Description

I want to create docker file for linksHub

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment] 2023-07-05 08:01
i guess its a nice idea, @CBID2 @ujjawaltyagii and @k-deepak04 what do you think?

**Comment by CBID2** [comment] 2023-07-05 14:28
> i guess its a nice idea, @CBID2 @ujjawaltyagii and @k-deepak04 what do you think?

I'm not familiar with Dockers so I want to know more about their benefits

**Comment by k-deepak04** [comment] 2023-07-05 18:06
> i guess its a nice idea, @CBID2 @ujjawaltyagii and @k-deepak04 what do you think?

yes we can go for that

**Comment by k-deepak04** [comment] 2023-07-05 18:09
> > i guess its a nice idea, @CBID2 @ujjawaltyagii and @k-deepak04 what do you think?
> 
> I'm not familiar with Dockers so I want to know more about their benefits

@CBID2 in simple terms, we can make our app portable,scalable and isolate to run in a proper container , scalability means if the app becomes famous or traffic is growing than we don't have to write all the things like load balancing and all, we can easily do that.

**Comment by CBID2** [comment] 2023-07-05 18:44
> > > i guess its a nice idea, @CBID2 @ujjawaltyagii and @k-deepak04 what do you think?
> 
> > 
> 
> > I'm not familiar with Dockers so I want to know more about their benefits
> 
> 
> 
> @CBID2 in simple terms, we can make our app portable,scalable and isolate to run in a proper container , scalability means if the app becomes famous or traffic is growing than we don't have to write all the things like load balancing and all, we can easily do that.

So in simple terms, dockerizing would lighten the work load for us?

**Comment by rupali-codes** [comment] 2023-07-06 17:56
this issue is duplicate of #1159

**Closed** 2023-07-06 21:03 UTC
Labels: 🔒 locked
