### ISSUE TITLE
[ADD] Languages - C++

### ISSUE THREAD

**Issue by srujana-16** [rupali-codes/LinksHub#1115] opened 2023-06-21 14:50 UTC
### Category Name

none

### Subcategory Name

C++

### Additional Context

I would like to add a subcategory under Languages - C++. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by CBID2** [comment] 2023-06-21 15:26
Hi @srujana-16! :) Just to confirm, you're in GSSOC right? :)

**Comment by rupali-codes** [comment] 2023-06-25 11:59
Closing this issue because its duplicate of #645 issue

**Closed by rupali-codes** 2023-06-25 11:59 UTC
Labels: chore, goal: new-category, 🔒 locked
