### ISSUE TITLE
[Add] <write what you want to add>

### ISSUE THREAD

**Issue by dfordp** [rupali-codes/LinksHub#1721] opened 2023-10-01 10:17 UTC
### Site URL

https://www.youtube.com/watch?v=yzeVMecydCE&t=1792s&ab_channel=freeCodeCamp.org

### Description of the above provided site

Learn why and how to contribute to open source software. You will learn about how to find projects to contribute to, how to make issues and PRs, how to make money from open source, and more.

### Category

Resources

### Sub Category

video link

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Anmol-Baranwal** [comment] 2023-10-02 11:36
@dfordp 
You surely don't want spam on your PR, right. You need to read `Contributing.md` before contributing.

Please don't rush things. Read everything properly and do it in a better way. It will be very great for your open source journey.

duplicate of #1731

**Closed by Anmol-Baranwal** 2023-10-02 11:36 UTC
Labels: goal: new-link, chore, 🔒 locked
