### ISSUE TITLE
feat: add searchbar for mobile devices (new design)

### ISSUE THREAD

**Issue by Anmol-Baranwal** [rupali-codes/LinksHub#2202] opened 2023-12-08 18:54 UTC
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

![image](https://github.com/rupali-codes/LinksHub/assets/74038190/da27a28d-d2af-46d2-9a40-228338d4e341)
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/2816a9df-5f6f-42fd-97bf-48fe2c9b9cc2)

> The design should be responsive. 

---

ℹ️ We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- The nav menu is implemented in `dev` branch, so make sure to fork the `dev` branch as well. Then you can use the existing code easily.

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---

**Comment by JoshiUtsav** [comment] 2023-12-08 20:36
@Anmol-Baranwal could you assign this to me.

**Comment by Anmol-Baranwal** [comment] 2023-12-09 06:24
> @Anmol-Baranwal could you assign this to me.

I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.

**Comment by heysolomon** [comment] 2023-12-26 01:35
Hey @Anmol-Baranwal can I jump on this?

**Comment by Anmol-Baranwal** [comment] 2023-12-26 11:25
> Hey @Anmol-Baranwal can I jump on this?

@JoshiUtsav 
Are you working on this? If not, let me know so I can assign `heysolomon`.

**Comment by JoshiUtsav** [comment] 2023-12-26 11:51
@Anmol-Baranwal assign this task to him.

**Comment by Anmol-Baranwal** [comment] 2023-12-26 19:37
> @Anmol-Baranwal assign this task to him.

@heysolomon 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance. 

Also, please let us know by when you can complete it. We usually don't ask, but in many recent high priority issues, people leave it unattended after getting assigned and unassign themselves after 25 days or a month.

Therefore, there is no strict time constraint, but we would appreciate it if you could provide an expected date. This date can, of course, be extended :)

**Comment by heysolomon** [comment] 2023-12-26 21:53
> > @Anmol-Baranwal assign this task to him.
> 
> @heysolomon I have assigned you the issue. Please proceed with it, and don't hesitate to tag any of the maintainers if you require any assistance.
> 
> Also, please let us know by when you can complete it. We usually don't ask, but in many recent high priority issues, people leave it unattended after getting assigned and unassign themselves after 25 days or a month.
> 
> Therefore, there is no strict time constraint, but we would appreciate it if you could provide an expected date. This date can, of course, be extended :)

Okay. I will be done on or before Friday this week.

**Comment by heysolomon** [comment] 2023-12-28 22:41
Hey @Anmol-Baranwal, after looking through the mobile view on local, I noticed there's no sidebar and the issue is titled: **add searchbar for mobile devices (new design)** 

I'm I supposed to build the sidebar? because the issue says `searchbar`.

**Closed** 2024-01-09 12:27 UTC
Labels: goal: new-design, 🚀 ready, priority: high
