### ISSUE TITLE
[BUG] Showing two meta images when sharing LinksHub link in discord

### ISSUE THREAD

**Issue by rupali-codes** [rupali-codes/LinksHub#2240] opened 2024-01-25 17:09 UTC
### Description

It's showing same image twice in the discord while sharing the LinksHub link. 

Kindly fix the og (open graph) tags for discord

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/78981177/92bff73f-8992-457e-8fc3-4f7e4e8134d2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

**Comment by WaqarTabish2807** [comment] 2024-01-26 14:49
Hey Rupali, Can you please add a few more screenshots? Because I can't see any difference at my end while sharing the link. Thanks

**Comment by Anmol-Baranwal** [comment] 2024-01-31 09:29
> Hey Rupali, Can you please add a few more screenshots? Because I can't see any difference at my end while sharing the link. Thanks

@rupali-codes 

We were getting this in preview, but it seems to be resolved now.
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/b701f4ef-b4d2-43d8-9dd0-e8987e741317)

It was definitely caused by duplicate meta tags, but I'm not sure what fixed the issue.

**Comment by Anmol-Baranwal** [comment] 2024-01-31 09:36
@WaqarTabish2807 
We will double-check to see if it is actually resolved and close the issue if everything seems fixed. Otherwise, we will let you know how to contribute.

**Closed** 2024-01-31 15:19 UTC
Labels: bug, good first issue, up for grabs, quick-fix, first-timers, priority: high
