### ISSUE TITLE
[BUG] <Dockerizing The application>

### ISSUE THREAD

**Issue by TripleteSumit** [rupali-codes/LinksHub#1224] opened 2023-07-04 15:51 UTC
### Description

This contribution adds **Docker support** to the project, enabling easy deployment and improved portability. **By Dockerizing the web app, I provide a streamlined and consistent environment for running the application across different systems**. Developer can benefit from simplified setup, isolated dependencies, and enhanced reproducibility. With Docker, **deploying the web app becomes more efficient and scalable.**

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rupali-codes** [comment] 2023-07-06 18:05
This closing is duplicate of #1159 please check all the issues carefully before raising any issues

**Closed** 2023-07-06 21:03 UTC
Labels: bug, 🔒 locked
