### ISSUE TITLE
[BUG] Navigation buttons overlapping bug

### ISSUE THREAD

**Issue by singodiyashubham87** [rupali-codes/LinksHub#1827] opened 2023-10-05 21:07 UTC
### Description

The button to navigate to different pages is overlapping the content of the page, I want to make its position static at the end of the cards list something like this:- 

![image](https://github.com/rupali-codes/LinksHub/assets/93720428/910e6a36-75fb-4c08-b3f0-e0c04481e50c)

Kindly assign me this issue under Hacktoberfest'23

### Screenshots

![image](https://github.com/rupali-codes/LinksHub/assets/93720428/54db8b81-35e7-42e7-a0c6-0664eee4dade)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

**Comment by rupali-codes** [comment] 2023-10-06 06:41
@singodiyashubham87 we're closing this issue because it's duplicate of #1808. Please check all the issues before raising any new issue and follow our CONTRIBUTING guidelines. Also, feel free to create any other issues. 

Thanks.

**Closed by rupali-codes** 2023-10-06 06:41 UTC
Labels: bug, 🔒 locked
