### ISSUE TITLE
ci:  add github actions

### ISSUE THREAD

**Issue by priyankarpal** [rupali-codes/LinksHub#365] opened 2023-03-21 14:45 UTC
### Description

- Need to add greetings.yml so when a user creates their first issue or PR GitHub Action will show a welcome message.
- JSON check GitHub Action to validate the JSON code.
- Dependabot action to up to date all GitHub Actions.

Created PR

**Comment by rupali-codes** [comment] 2023-03-21 15:53
This issue is duplicate of #339

**Closed** 2023-03-22 05:44 UTC
Labels: duplicate
