### ISSUE TITLE
[BUG] Sidebar sections don't auto expand on search.

### ISSUE THREAD

**Issue by shoebilyas123** [rupali-codes/LinksHub#669] opened 2023-05-23 05:44 UTC
### Description

When we search on LinksHub, it displays the result. However, the sidebar accordion under which the result is present, does not expand unless we manually click and expand it. It should auto expand lest it delivers a bad UX.
Moreover, when we expand one section, it should not close the other one. The reason is same - bad UX.

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/73349037/21e09079-ba8f-4041-b8d1-0e5eaae87612

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Isha988** [comment] 2023-05-23 06:52
@shoebilyas123 I am a gssoc'23 contributor and I want to work on this issue.
Would you please assign it to me!?

**Comment by rupali-codes** [comment] 2023-05-23 08:03
> @shoebilyas123 I am a gssoc'23 contributor and I want to work on this issue. Would you please assign it to me!?

Hey Isha, it's great to have you, but please read CONTRIBUTING guidelines carefully. When author of the issue is willing to work on the issue we can not assign the issue to anyone else. You can look for any other issue :)

**Comment by Isha988** [comment] 2023-05-23 08:20
> > @shoebilyas123 I am a gssoc'23 contributor and I want to work on this issue. Would you please assign it to me!?
> 
> Hey Isha, it's great to have you, but please read CONTRIBUTING guidelines carefully. When author of the issue is willing to work on the issue we can not assign the issue to anyone else. You can look for any other issue :)

Okay, No problem

**Closed** 2023-05-23 15:12 UTC
Labels: bug, frontend

**Comment by shoebilyas123** [comment] 2023-05-23 17:49
> Hello everyone, Just commenting that we don't go back and forth on this feature. Please read this issue #513 and the PR #669 that has been recently merged. This behavior was a feature request and not a bug. I still think that we should keep the only one tab normally but if search is enabled we can disable one tab behavior. @Isha988 @rupali-codes @shoebilyas123 . Please check it before merging.

Thank you! I'll make sure to check thoroughly before creating any issue,

**Comment by rupali-codes** [comment] 2023-05-24 14:57
> Hello everyone, Just commenting that we don't go back and forth on this feature. Please read this issue #513 and the PR #669 that has been recently merged. This behavior was a feature request and not a bug. I still think that we should keep the only one tab normally but if search is enabled we can disable one tab behavior. @Isha988 @rupali-codes @shoebilyas123 . Please check it before merging.

Thanks
